### ISSUE TITLE
Translation string and baf missing

### ISSUE THREAD

**Issue by arosenow** [Gibberlings3/Ajantis_BG1_Expansion#12]
Hi, 

This translation string and the shield file are both missing in the repository

/* BG1NPC: shield */
ACTION_IF (FILE_EXISTS_IN_GAME ~override/x#ajshld.itm~) THEN BEGIN
PRINT @90007 /* ~BG1NPC detected.~ */
  EXTEND_BOTTOM ~BDAJANTI.bcs~ ~ajantisbg1/ajantissod/crossmod/bg1npc_shield.baf~ EVALUATE_BUFFER
END

**Comment by Gitjas** [comment]
Path to bg1npc_shield.baf: https://github.com/Gibberlings3/Ajantis_BG1_Expansion/blob/master/ajantisbg1/ajantissod/crossmod/bg1npc_shield.baf
The line @90007  = ~BG1NPC detected.~ is in setup-ajantisbg1.tra for all language versions.
Closing this.
